// Generated by https://quicktype.io

export interface ItemsResponse {
  site_id:                   SiteID;
  country_default_time_zone: string;
  query:                     string;
  paging:                    Paging;
  results:                   Result[];
  sort:                      Sort;
  available_sorts:           Sort[];
  filters:                   Filter[];
  available_filters:         AvailableFilter[];
}

export interface AvailableFilter {
  id:     string;
  name:   string;
  type:   string;
  values: AvailableFilterValue[];
}

export interface AvailableFilterValue {
  id:      string;
  name:    string;
  results: number;
}

export interface Sort {
  id:   null | string;
  name: string;
}

export interface Filter {
  id:     string;
  name:   string;
  type:   string;
  values: FilterValue[];
}

export interface FilterValue {
  id:              string;
  name:            string;
  path_from_root?: Sort[];
}

export interface Paging {
  total:           number;
  primary_results: number;
  offset:          number;
  limit:           number;
}

export interface Result {
  id:                    string;
  site_id:               SiteID;
  title:                 string;
  seller:                Seller;
  price:                 number;
  prices:                Prices;
  sale_price:            null;
  currency_id:           CurrencyID;
  available_quantity:    number;
  sold_quantity:         number;
  buying_mode:           BuyingMode;
  listing_type_id:       ListingTypeID;
  stop_time:             string;
  condition:             Condition;
  permalink:             string;
  thumbnail:             string;
  thumbnail_id:          string;
  accepts_mercadopago:   boolean;
  installments:          Installments;
  address:               Address;
  shipping:              Shipping;
  seller_address:        SellerAddress;
  attributes:            Attribute[];
  original_price:        number | null;
  category_id:           CategoryID;
  official_store_id:     number | null;
  domain_id:             DomainID;
  catalog_product_id:    string;
  tags:                  ResultTag[];
  catalog_listing?:      boolean;
  use_thumbnail_id:      boolean;
  offer_score:           null;
  offer_share:           null;
  match_score:           null;
  winner_item_id:        null;
  melicoin:              null;
  discounts:             null;
  order_backend:         number;
  differential_pricing?: DifferentialPricing;
}

export interface Address {
  state_id:   StateID;
  state_name: StateName;
  city_id:    null | string;
  city_name:  string;
}

export enum StateID {
  ArB = "AR-B",
  ArC = "AR-C",
  ArN = "AR-N",
  ArS = "AR-S",
}

export enum StateName {
  BuenosAires = "Buenos Aires",
  CapitalFederal = "Capital Federal",
  Misiones = "Misiones",
  SantaFe = "Santa Fe",
}

export interface Attribute {
  value_name:           string;
  values:               AttributeValue[];
  id:                   ID;
  name:                 Name;
  attribute_group_id:   AttributeGroupID;
  attribute_group_name: AttributeGroupName;
  source:               number;
  value_id:             null | string;
  value_struct:         Struct | null;
}

export enum AttributeGroupID {
  Others = "OTHERS",
}

export enum AttributeGroupName {
  Otros = "Otros",
}

export enum ID {
  Brand = "BRAND",
  GPUModel = "GPU_MODEL",
  ItemCondition = "ITEM_CONDITION",
  Line = "LINE",
  Model = "MODEL",
  ProcessorModel = "PROCESSOR_MODEL",
  Weight = "WEIGHT",
}

export enum Name {
  CondiciónDelÍtem = "Condición del ítem",
  Línea = "Línea",
  Marca = "Marca",
  Modelo = "Modelo",
  ModeloDeGPU = "Modelo de GPU",
  ModeloDelProcesador = "Modelo del procesador",
  Peso = "Peso",
}

export interface Struct {
  number: number;
  unit:   Unit;
}

export enum Unit {
  G = "g",
}

export interface AttributeValue {
  id:     null | string;
  name:   string;
  struct: Struct | null;
  source: number;
}

export enum BuyingMode {
  BuyItNow = "buy_it_now",
}

export enum CategoryID {
  Mla1055 = "MLA1055",
}

export enum Condition {
  New = "new",
}

export enum CurrencyID {
  Ars = "ARS",
}

export interface DifferentialPricing {
  id: number;
}

export enum DomainID {
  MlaCellphones = "MLA-CELLPHONES",
}

export interface Installments {
  quantity:    number;
  amount:      number;
  rate:        number;
  currency_id: CurrencyID;
}

export enum ListingTypeID {
  GoldPro = "gold_pro",
  GoldSpecial = "gold_special",
}

export interface Prices {
  id:                    string;
  prices:                Price[];
  presentation:          Presentation;
  payment_method_prices: any[];
  reference_prices:      Price[];
  purchase_discounts:    any[];
}

export interface Presentation {
  display_currency: CurrencyID;
}

export interface Price {
  id:                    string;
  type:                  Type;
  amount:                number;
  regular_amount?:       number | null;
  currency_id:           CurrencyID;
  last_updated:          string;
  conditions:            Conditions;
  exchange_rate_context: ExchangeRateContext;
  metadata?:             Metadata;
  tags?:                 any[];
}

export interface Conditions {
  context_restrictions: ContextRestriction[];
  start_time:           null | string;
  end_time:             null | string;
  eligible:             boolean;
}

export enum ContextRestriction {
  ChannelMarketplace = "channel_marketplace",
  ChannelMshops = "channel_mshops",
}

export enum ExchangeRateContext {
  Default = "DEFAULT",
}

export interface Metadata {
  promotion_id?:   string;
  promotion_type?: PromotionType;
}

export enum PromotionType {
  Custom = "custom",
}

export enum Type {
  MinStandard = "min_standard",
  Promotion = "promotion",
  Standard = "standard",
  Was = "was",
}

export interface Seller {
  id:                 number;
  permalink:          string;
  registration_date:  string;
  car_dealer:         boolean;
  real_estate_agency: boolean;
  tags:               SellerTag[];
  seller_reputation:  SellerReputation;
  eshop?:             Eshop;
}

export interface Eshop {
  seller:           number;
  eshop_rubro:      null;
  eshop_id:         number;
  nick_name:        string;
  site_id:          SiteID;
  eshop_logo_url:   string;
  eshop_status_id:  number;
  eshop_experience: number;
  eshop_locations:  any[];
}

export enum SiteID {
  Mla = "MLA",
}

export interface SellerReputation {
  power_seller_status:  PowerSellerStatus | null;
  level_id:             LevelID | null;
  metrics:              Metrics;
  transactions:         Transactions;
  real_level?:          RealLevel;
  protection_end_date?: string;
}

export enum LevelID {
  The3_Yellow = "3_yellow",
  The4_LightGreen = "4_light_green",
  The5_Green = "5_green",
}

export interface Metrics {
  cancellations:         Cancellations;
  claims:                Cancellations;
  delayed_handling_time: Cancellations;
  sales:                 Sales;
}

export interface Cancellations {
  period:    CancellationsPeriod;
  rate:      number;
  value:     number;
  excluded?: Excluded;
}

export interface Excluded {
  real_value: number;
  real_rate:  number;
}

export enum CancellationsPeriod {
  The365Days = "365 days",
  The60Days = "60 days",
}

export interface Sales {
  period:    CancellationsPeriod;
  completed: number;
}

export enum PowerSellerStatus {
  Gold = "gold",
  Platinum = "platinum",
  Silver = "silver",
}

export enum RealLevel {
  Green = "green",
  Yellow = "yellow",
}

export interface Transactions {
  canceled:  number;
  period:    TransactionsPeriod;
  total:     number;
  ratings:   Ratings;
  completed: number;
}

export enum TransactionsPeriod {
  Historic = "historic",
}

export interface Ratings {
  negative: number;
  neutral:  number;
  positive: number;
}

export enum SellerTag {
  Brand = "brand",
  CreditsActiveBorrower = "credits_active_borrower",
  CreditsOpenMarket = "credits_open_market",
  CreditsPriority2 = "credits_priority_2",
  CreditsPriority4 = "credits_priority_4",
  CreditsProfile = "credits_profile",
  Eshop = "eshop",
  LargeSeller = "large_seller",
  MessagesAsSeller = "messages_as_seller",
  Mshops = "mshops",
  Normal = "normal",
}

export interface SellerAddress {
  id:           string;
  comment:      string;
  address_line: string;
  zip_code:     string;
  country:      Sort;
  state:        Sort;
  city:         Sort;
  latitude:     string;
  longitude:    string;
}

export interface Shipping {
  free_shipping: boolean;
  mode:          Mode;
  tags:          ShippingTag[];
  logistic_type: LogisticType;
  store_pick_up: boolean;
}

export enum LogisticType {
  CrossDocking = "cross_docking",
  DropOff = "drop_off",
  XdDropOff = "xd_drop_off",
}

export enum Mode {
  Me2 = "me2",
}

export enum ShippingTag {
  MandatoryFreeShipping = "mandatory_free_shipping",
  SelfServiceIn = "self_service_in",
  SelfServiceOut = "self_service_out",
}

export enum ResultTag {
  BestSellerCandidate = "best_seller_candidate",
  BrandVerified = "brand_verified",
  CartEligible = "cart_eligible",
  ExtendedWarrantyEligible = "extended_warranty_eligible",
  GoodQualityPicture = "good_quality_picture",
  GoodQualityThumbnail = "good_quality_thumbnail",
  ImmediatePayment = "immediate_payment",
  IncompleteTechnicalSpecs = "incomplete_technical_specs",
  LoyaltyDiscountEligible = "loyalty_discount_eligible",
  MeliChoiceCandidate = "meli_choice_candidate",
  PoorQualityPicture = "poor_quality_picture",
  ShippingGuaranteed = "shipping_guaranteed",
  StandardPriceByChannel = "standard_price_by_channel",
}
